# Generated by Django 2.1.7 on 2019-05-23 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mysite', '0002_register'),
    ]

    operations = [
        migrations.CreateModel(
            name='postadd',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(blank=True, max_length=250)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='adds/%Y/%m/%d')),
                ('img2', models.ImageField(blank=True, null=True, upload_to='adds/%Y/%m/%d')),
                ('img3', models.ImageField(blank=True, null=True, upload_to='adds/%Y/%m/%d')),
                ('img4', models.ImageField(blank=True, null=True, upload_to='adds/%Y/%m/%d')),
                ('city', models.CharField(blank=True, max_length=250)),
                ('status', models.BooleanField(default=True)),
                ('on_date', models.DateField(auto_now_add=True)),
                ('on_time', models.TimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
