# Generated by Django 2.1.7 on 2019-05-23 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_postadd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postadd',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mysite.register'),
        ),
    ]
