# Generated by Django 2.1.7 on 2019-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0005_postadd_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='postadd',
            name='views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
