# Generated by Django 2.1.7 on 2019-05-26 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_postadd_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250)),
                ('email', models.EmailField(blank=True, max_length=250)),
                ('contact', models.IntegerField()),
                ('msz', models.TextField()),
                ('on_date', models.DateField(auto_now_add=True)),
                ('on_time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
